In [1]:
#veri işlemek için kütpahane
import pandas as pd

#garikler için kütpahanemiz 
import seaborn as sns
import matplotlib.pyplot as plt

#regresyon modeli için kütpahanemiz
from sklearn.linear_model import LinearRegression

In [2]:
# df yani dataFrame adında bir tablo oluşturuyoruz ve veriyi yüklüyoruz
df = pd.read_csv("advertising.csv")

#tablonun ilk birkaç verisini görmek için
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
# bağımsız değişkeni yani girdiyi atama
X = df[["TV"]]

# bağımlı değişkeni yani çıktıyı atama
y = df["sales"]

# X verisinin ilk bikaç verisini kontol edelim
X.head()

TV
0  230.1
1   44.5
2   17.2
3  151.5
4  180.8

In [4]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [7]:
# 1. Modeli Tanımlama: reg adında bir doğrusal regresyon makinesi oluşturuyoruz
reg = LinearRegression()

#2.modeli eğitme (fit etme)Makineye X (TV harcaması) ve y (Satış) arasındaki ilişkiyi öğret diyoruz.
# Bu, b0 ve b1 katsayılarını bulduğu aşamadır.
model = reg.fit(X, y)

In [6]:
# Kesişim Noktası (b0): model.intercept_
print("Kesişim Noktası (b0):", model.intercept_)

# Eğim (b1): model.coef_
print("Eğim (b1):", model.coef_)

Kesişim Noktası (b0): 7.032593549127695
Eğim (b1): [0.04753664]


In [8]:
# R-Kare (R^2) skorunu hesaplama
r_kare = model.score(X, y)
print("R-Kare Skoru:", r_kare)

R-Kare Skoru: 0.611875050850071


Artıklar ve Makine Öğrenmesindeki Önemi

In [9]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [11]:
model.predict(X)[0:6]

array([17.97077451,  9.14797405,  7.85022376, 14.23439457, 15.62721814,
        7.44616232])

In [12]:
y[0:10]

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
5     7.2
6    11.8
7    13.2
8     4.8
9    10.6
Name: sales, dtype: float64

In [13]:
X[0:6]

TV
0  230.1
1   44.5
2   17.2
3  151.5
4  180.8
5    8.7

X[0:6]: Bu, size veri setinizin bağımsız değişkeni olan X'in (bizim örneğimizde TV Harcamaları) ilk 6 satırını gösterdi.

y[0:10]: Bu size veri setindeki gerçek satış değerlerini gösterir. Bunlar, geçmişte gerçekleşmiş sonuçlardır.

model.predict(X)[0:6]: Bu size modelin, X (TV harcaması) verilerine dayanarak hesapladığı ve tahmin ettiği satış değerlerini gösterir.

In [13]:
X[0:6]

TV
0  230.1
1   44.5
2   17.2
3  151.5
4  180.8
5    8.7

In [14]:
model.predict(X)[0:6]

array([17.97077451,  9.14797405,  7.85022376, 14.23439457, 15.62721814,
        7.44616232])

In [15]:
gercek_y = y[0:10]

In [16]:
gercek_y

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
5     7.2
6    11.8
7    13.2
8     4.8
9    10.6
Name: sales, dtype: float64

In [17]:
tahmin_edilen_y = model.predict(X)[0:10]

In [18]:
tahmin_edilen_y

array([17.97077451,  9.14797405,  7.85022376, 14.23439457, 15.62721814,
        7.44616232,  9.76595037, 12.74649773,  7.44140866, 16.53041431])

In [20]:
tahmin_edilen_y = pd.DataFrame(model.predict(X)[0:10])

In [21]:
hatalar = pd.concat([gercek_y, tahmin_edilen_y], axis = 1)

In [22]:
hatalar

sales          0
0   22.1  17.970775
1   10.4   9.147974
2    9.3   7.850224
3   18.5  14.234395
4   12.9  15.627218
5    7.2   7.446162
6   11.8   9.765950
7   13.2  12.746498
8    4.8   7.441409
9   10.6  16.530414

In [24]:
hatalar.columns = ["gercek_y", "tahmin_edilen_y"]

In [25]:
hatalar

gercek_y  tahmin_edilen_y
0      22.1        17.970775
1      10.4         9.147974
2       9.3         7.850224
3      18.5        14.234395
4      12.9        15.627218
5       7.2         7.446162
6      11.8         9.765950
7      13.2        12.746498
8       4.8         7.441409
9      10.6        16.530414

In [29]:
hatalar["hata"] = hatalar["gercek_y"] - hatalar["tahmin_edilen_y"]

In [30]:
hatalar

gercek_y  tahmin_edilen_y      hata
0      22.1        17.970775  4.129225
1      10.4         9.147974  1.252026
2       9.3         7.850224  1.449776
3      18.5        14.234395  4.265605
4      12.9        15.627218 -2.727218
5       7.2         7.446162 -0.246162
6      11.8         9.765950  2.034050
7      13.2        12.746498  0.453502
8       4.8         7.441409 -2.641409
9      10.6        16.530414 -5.930414

In [31]:
hatalar["hata_kareler"] = hatalar["hata"]**2

In [32]:
hatalar

gercek_y  tahmin_edilen_y      hata  hata_kareler
0      22.1        17.970775  4.129225     17.050503
1      10.4         9.147974  1.252026      1.567569
2       9.3         7.850224  1.449776      2.101851
3      18.5        14.234395  4.265605     18.195390
4      12.9        15.627218 -2.727218      7.437719
5       7.2         7.446162 -0.246162      0.060596
6      11.8         9.765950  2.034050      4.137358
7      13.2        12.746498  0.453502      0.205664
8       4.8         7.441409 -2.641409      6.977040
9      10.6        16.530414 -5.930414     35.169814

In [35]:
import numpy as np
np.mean(hatalar["hata_kareler"])

np.float64(9.290350329638102)